services:
  - type: web
    name: homeservice
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: homeservice
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
databases:
  - name: homeservice
    databaseName: homeservice
