<<<<<<< HEAD
services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: homeservice
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false

databases:
  - name: homeservice
    databaseName: homeservice
    user: postgres
    password: 1234
=======
services:
  - type: web
    name: homeservice
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: homeservice
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
databases:
  - name: homeservice
    databaseName: homeservice
>>>>>>> 372e66599e200dd1a46ec227c0976d6925fe303e
