# Generated by Django 4.2.7 on 2025-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='worker_specifically_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
