# Generated by Django 4.2.7 on 2025-05-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0004_response_worker_specifically_chosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='scheduled_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (12:00 PM - 4:00 PM)'), ('evening', 'Evening (4:00 PM - 8:00 PM)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequests',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequests',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (12:00 PM - 4:00 PM)'), ('evening', 'Evening (4:00 PM - 8:00 PM)')], max_length=20, null=True),
        ),
    ]
