# Generated by Django 4.2.7 on 2025-05-04 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0005_response_estimated_hours_response_scheduled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_available', models.BooleanField(default=True)),
                ('afternoon_available', models.BooleanField(default=True)),
                ('evening_available', models.BooleanField(default=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeServices_app.workers')),
            ],
            options={
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
